{% set name = "perl-compress-raw-bzip2" %}
{% set version = "2.213" %}
{% set sha256 = "8d75d3d366c9101ca18061b00d438d3da39478c06159147dea3c666770577c7b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Bzip2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test -j"${CPU_COUNT}"  # [build_platform == target_platform]
    - make install VERBINST=1

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Compress::Raw::Bzip2

about:
  home: "https://metacpan.org/pod/Compress::Raw::Bzip2"
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: "Low-Level Interface to bzip2 compression library."
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  doc_url: "https://metacpan.org/pod/Compress::Raw::Bzip2"

extra:
  recipe-maintainers:
    - conda-forge/perl-packagers
